export const data = [
  {
    title: "Burger#1",
    seller: "Burger",
    img: "1",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#2",
    seller: "Burger",
    img: "2",
    price: 15,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#3",
    seller: "Burger",
    img: "3",
    price: 40,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#4",
    seller: "Burger",
    img: "4",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#5",
    seller: "Burger",
    img: "5",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#6",
    seller: "Burger",
    img: "6",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#7",
    seller: "Burger",
    img: "7",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#8",
    seller: "Burger",
    img: "8",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#9",
    seller: "Burger",
    img: "9",
    price: 30,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Burger#10",
    seller: "Burger",
    img: "10",
    price: 25,
    weight: 300,
    recipe: "Lorem",
  },

  {
    title: "Pizza#1",
    seller: "Pizza",
    img: "1",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#2",
    seller: "Pizza",
    img: "2",
    price: 15,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#3",
    seller: "Pizza",
    img: "3",
    price: 40,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#4",
    seller: "Pizza",
    img: "4",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#5",
    seller: "Pizza",
    img: "5",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#6",
    seller: "Pizza",
    img: "6",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#7",
    seller: "Pizza",
    img: "7",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#8",
    seller: "Pizza",
    img: "8",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#9",
    seller: "Pizza",
    img: "9",
    price: 30,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Pizza#10",
    seller: "Pizza",
    img: "10",
    price: 25,
    weight: 300,
    recipe: "Lorem",
  },

  {
    title: "Sushi#1",
    seller: "Sushi",
    img: "1",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#2",
    seller: "Sushi",
    img: "2",
    price: 15,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#3",
    seller: "Sushi",
    img: "3",
    price: 40,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#4",
    seller: "Sushi",
    img: "4",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#5",
    seller: "Sushi",
    img: "5",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#6",
    seller: "Sushi",
    img: "6",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#7",
    seller: "Sushi",
    img: "7",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#8",
    seller: "Sushi",
    img: "8",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#9",
    seller: "Sushi",
    img: "9",
    price: 30,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Sushi#10",
    seller: "Sushi",
    img: "10",
    price: 25,
    weight: 300,
    recipe: "Lorem",
  },

  {
    title: "Vegan#1",
    seller: "Vegan",
    img: "1",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#2",
    seller: "Vegan",
    img: "2",
    price: 15,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#3",
    seller: "Vegan",
    img: "3",
    price: 40,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#4",
    seller: "Vegan",
    img: "4",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#5",
    seller: "Vegan",
    img: "5",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#6",
    seller: "Vegan",
    img: "6",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#7",
    seller: "Vegan",
    img: "7",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#8",
    seller: "Vegan",
    img: "8",
    price: 20,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#9",
    seller: "Vegan",
    img: "9",
    price: 30,
    weight: 300,
    recipe: "Lorem",
  },
  {
    title: "Vegan#10",
    seller: "Vegan",
    img: "10",
    price: 25,
    weight: 300,
    recipe: "Lorem",
  },
];
 
 